apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeiro-dp
  labels:
    app: primeiro-app
    type: frontend
spec:
  template:
    metadata:
      labels:
        app: primeiro-pod
        type: frontend
  spec:
      container:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_HOST
            value: mysql-svc
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DB
            value: db_example
          - name: MYSQL_PASS
            value: "123456"
  selector:
    matchLabels:
      type: frontend
